server:
  port: 8080
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: "debug"
spring:
  h2:
    console:
      enabled: true # activo consola de h2
  datasource:
    url: "jdbc:h2:mem:testdb"   # jdbc es protocolo, h2 base de datos, mem porque es en memoria y testdb es el nombre
---
spring:
  config:
    activate:
      on-profile: "desarrollo"
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: "pruebas"
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: "produccion"
server:
  port: 9000