server:
  port: 8080
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: "debug"
spring:
  h2:
    console:
      enabled: true # activate localhost:8080/h2-console
  datasource:
    url: "jdbc:h2:mem:testdb"   # jdbc = protocol, h2 = database type, mem = in-memory, testdb database name
  jpa:
    hibernate:
      ddl-auto: "none" # tell spring to no generate the schema, we are generating it
---
spring:
  config:
    activate:
      on-profile: "desarrollo"
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: "pruebas"
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: "produccion"
server:
  port: 9000